name: On PRs - Linux Special Builds

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  special_debugRelease:
    name: 'Ubuntu 20.04 - GCC - Debug+Coverage'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          # Trying to deal with warning: ->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0

      - name: install dependencies
        run: |
          pip3 install conan==1.54.0
          pip3 install gcovr

      - name: Get Dependencies
        run: |
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan install . -pr:b=default -pr:h=default -pr:h=./conan/dev --build missing

      - name: Build
        run: conan build .

      - name: Tests + Upload coverage
        run: |
          ctest --verbose --output-on-failure --test-dir ./build/Debug
          # this needs to match th ecommand in on_push_ExtraJobsForMain.yml!
          gcovr --root . --object-dir ./build/Debug --exclude-unreachable-branches --exclude-throw-branches --xml -o coverage.xml
          curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
          gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
          shasum -a 256 -c codecov.SHA256SUM
          chmod +x codecov
          ls -lh
          ./codecov -f coverage.xml

